### ISSUE TITLE
addFiles property seems missleading

### ISSUE THREAD

**Issue by BonneVoyager** [flipace/react-themeit#4]
addFiles property was misleading for me at first. With something like addThemeFiles or addStyleFiles it would be quite obvious what the property does.

**Comment by flipace** [comment]
Good point.

I think "addStyleFiles" may be a better choice here.

Want to give it a spin with a PR?

**Comment by BonneVoyager** [comment]
Yes, thank you. I will push a PR sometime soon.

**Comment by flipace** [comment]
thanks!
